### ISSUE TITLE
CSV files in data folder

### ISSUE THREAD

**Issue by tusharGitHub13** [Andrej1A/DataScienceExamples#1]
Can you create a data folder and upload all CSV files so when we download your project we can have the same files and similar paths in the notebook instead of downloading separately on our computers.

**Comment by Andrej1A** [comment]
Thank you for your message. I haven't done this, because I was not sure about the license of the dataset, but it should be ok. I uploaded the dataset to the master branch inside the folder: _./world_population/data/_

**Comment by tusharGitHub13** [comment]
Thanks Andrej.
